# Constants File 

# Packet Types 
DATA_PACKET_ACKNOWLEDGEMENT_TYPE = "ACK_DATA"
DATA_PACKET_TYPE = "DATA"

# Network Element Class Identifiers
HOST_ELEMENT = "HOST"
ROUTER_ELEMENT = "ROUTER"
LINK_ELEMENT = "LINK"
FLOW_DATA_SOURCE_ELEMENT = "FLOW, DATA SOURCE"
FLOW_DATA_SINK_ELEMENT = "FLOW, DATA SINK"